### ISSUE TITLE
Unable to upload django-cms 2.4.2

### ISSUE THREAD

**Issue by chaica** [mvantellingen/localshop#105] opened 2014-06-24 09:58 UTC
Hi,

While trying to upload django-cms 2.4.2 to my localshop, I do have a 400 bad request. It perfectly works with other packages so I guess it comes from the django-cms metadata. But I'm not able to find proper logs to troubleshoot more precisely the issue.

archive : https://pypi.python.org/packages/source/d/django-cms/django-cms-2.4.2.tar.gz#md5=028423945d41c7fad55e7605568a089e

**Comment by canassa** [comment] 2015-01-18 03:34
I was unable to reproduce this issue with the current localshop release. Therefore, I am closing this issue.

**Closed by canassa** 2015-01-18 03:34 UTC
Labels: bug, upload
