### ISSUE TITLE
issue with ~ (tilde) symbol when mirroring from files hosted in home directories

### ISSUE THREAD

**Issue by timhughes** [mvantellingen/localshop#55] opened 2013-04-03 01:25 UTC
The dulwich package url is http://samba.org/~jelmer/dulwich/dulwich-0.8.7.tar.gz but the tilde symbol gets converted to '%7e' and makes it fail.

```
Downloading/unpacking dulwich
  Getting page http://media.co.goldfish:8000/simple/dulwich
  URLs to search for versions for dulwich:
  * http://media.co.goldfish:8000/simple/dulwich/
  Getting page http://samba.org/%7ejelmer/dulwich
  Could not fetch URL http://samba.org/%7ejelmer/dulwich/dulwich-0.8.7.tar.gz (from http://media.co.goldfish:8000/simple/dulwich/): HTTP Error 301: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Permanently
  Will skip URL http://samba.org/%7ejelmer/dulwich/dulwich-0.8.7.tar.gz when looking for download links for dulwich
```

**Comment by canassa** [comment] 2015-01-18 04:06
I think that external packages got deprecated recently. Currently, dulwich is hosted on PyPI so I was not able to reproduce this problem. I am closing this issue for now.

**Closed by canassa** 2015-01-18 04:06 UTC
Labels: bug, mirroring
